# Generated by Django 4.2 on 2023-05-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_menu_item_in_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
